# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rzilla
email: rzilla@piccolboni.info
description: > # this means to ignore newlines until "baseurl:"
  A site for R, big data and open source practitioners
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rzilla.org" # the base hostname & protocol for your site
twitter_username: rzillaproj
github_username:  rzilla

# Build settings
markdown: kramdown
